# Generated by Django 5.2.8 on 2026-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("B_id", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("author", models.CharField()),
                ("pages", models.IntegerField()),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
