# Generated by Django 5.2.8 on 2026-07-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lsm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="count",
            field=models.IntegerField(default=10, max_length=2),
            preserve_default=False,
        ),
    ]
