# Generated by Django 5.2.8 on 2026-07-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lsm", "0002_book_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="count",
        ),
    ]
